// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpobserver

import (
	"io"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHttpClient creates a new instance of MockHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpClient {
	mock := &MockHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHttpClient is an autogenerated mock type for the HttpClient type
type MockHttpClient struct {
	mock.Mock
}

type MockHttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpClient) EXPECT() *MockHttpClient_Expecter {
	return &MockHttpClient_Expecter{mock: &_m.Mock}
}

// Post provides a mock function for the type MockHttpClient
func (_mock *MockHttpClient) Post(url string, contentType string, body io.Reader) (*http.Response, error) {
	ret := _mock.Called(url, contentType, body)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader) (*http.Response, error)); ok {
		return returnFunc(url, contentType, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader) *http.Response); ok {
		r0 = returnFunc(url, contentType, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = returnFunc(url, contentType, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHttpClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockHttpClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - contentType string
//   - body io.Reader
func (_e *MockHttpClient_Expecter) Post(url interface{}, contentType interface{}, body interface{}) *MockHttpClient_Post_Call {
	return &MockHttpClient_Post_Call{Call: _e.mock.On("Post", url, contentType, body)}
}

func (_c *MockHttpClient_Post_Call) Run(run func(url string, contentType string, body io.Reader)) *MockHttpClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHttpClient_Post_Call) Return(resp *http.Response, err error) *MockHttpClient_Post_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *MockHttpClient_Post_Call) RunAndReturn(run func(url string, contentType string, body io.Reader) (*http.Response, error)) *MockHttpClient_Post_Call {
	_c.Call.Return(run)
	return _c
}
