// reset is a code generator that produces Reset() methods for structs marked
// with "// generate:reset". It works on a per-package basis and only considers
// resettable types declared in the same package. Type aliases and generic
// structs declared in the same package are supported with the following
// limitations:
//   - Resettable types imported from other packages are not detected.
//   - Aliases to pointer types are not treated as resettable.
//   - Type parameters are reset to their zero value (T{}).
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rs/zerolog/log"
)

const (
	generateMarker = "// generate:reset"
	generatedFile  = "reset.gen.go"
)

type structInfo struct {
	name   string
	typ    *ast.StructType
	params *ast.FieldList
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	root = strings.TrimSuffix(root, "/...")
	if root == "" {
		root = "."
	}
	root = filepath.Clean(root)

	if err := filepath.WalkDir(
		root, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if !d.IsDir() {
				return nil
			}
			if shouldSkipDir(path) {
				return filepath.SkipDir
			}
			return processPackage(path)
		},
	); err != nil {
		if _, err = fmt.Fprintf(os.Stderr, "reset: %v\n", err); err != nil {
			log.Error().Err(err).Msg("error while print error")
		}
		os.Exit(1)
	}
}

func shouldSkipDir(path string) bool {
	base := filepath.Base(path)
	return base == ".git" || base == "vendor" || strings.HasPrefix(base, ".")
}

func processPackage(dir string) error {
	files, err := findGoFiles(dir)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return nil
	}

	fset := token.NewFileSet()
	parsedFiles := make([]*ast.File, 0, len(files))
	pkgName := ""

	for _, f := range files {
		var pf *ast.File
		pf, err = parser.ParseFile(fset, f, nil, parser.ParseComments|parser.AllErrors)
		if err != nil {
			return fmt.Errorf("parse %s: %w", f, err)
		}
		parsedFiles = append(parsedFiles, pf)
		if pkgName == "" && !strings.HasSuffix(pf.Name.Name, "_test") {
			pkgName = pf.Name.Name
		}
	}
	if pkgName == "" {
		return nil
	}

	resettableTypes := collectResettableTypes(parsedFiles)
	structs := collectStructsToGenerate(parsedFiles)
	if len(structs) == 0 {
		return nil
	}

	sort.Slice(
		structs, func(i, j int) bool {
			return structs[i].name < structs[j].name
		},
	)

	var buf bytes.Buffer
	if _, err = fmt.Fprintf(
		&buf, "// Code generated by reset tool; DO NOT EDIT.\n\npackage %s\n\n", pkgName,
	); err != nil {
		log.Error().Err(err).Msg("error while print")
	}

	for _, s := range structs {
		buf.WriteString(generateResetMethod(s, resettableTypes, fset))
	}

	out := filepath.Join(dir, generatedFile)
	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format %s: %w", out, err)
	}

	return os.WriteFile(out, formatted, 0o600)
}

func findGoFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") {
			continue
		}
		if name == generatedFile || strings.HasSuffix(name, "_gen.go") {
			continue
		}
		files = append(files, filepath.Join(dir, name))
	}
	return files, nil
}

func hasMarker(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(c.Text) == generateMarker {
			return true
		}
	}
	return false
}

func forEachMarkedTypeSpec(files []*ast.File, fn func(*ast.TypeSpec)) {
	for _, pf := range files {
		for _, decl := range pf.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE || !hasMarker(gen.Doc) {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if ok {
					fn(ts)
				}
			}
		}
	}
}

func collectResettableTypes(files []*ast.File) map[string]bool {
	types := make(map[string]bool)
	aliases := make(map[string]string)

	forEachMarkedTypeSpec(
		files, func(ts *ast.TypeSpec) {
			if _, ok := ts.Type.(*ast.StructType); ok {
				types[ts.Name.Name] = true
				return
			}
			if !ts.Assign.IsValid() {
				return
			}
			if _, ok := ts.Type.(*ast.StarExpr); ok {
				return
			}
			base := baseNameForResettableCheck(ts.Type)
			if base != "" {
				aliases[ts.Name.Name] = base
			}
		},
	)

	for changed := true; changed; {
		changed = false
		for alias, underlying := range aliases {
			if !types[alias] && types[underlying] {
				types[alias] = true
				changed = true
			}
		}
	}
	return types
}

func collectStructsToGenerate(files []*ast.File) []structInfo {
	var structs []structInfo
	forEachMarkedTypeSpec(
		files, func(ts *ast.TypeSpec) {
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return
			}
			structs = append(
				structs, structInfo{
					name:   ts.Name.Name,
					typ:    st,
					params: ts.TypeParams,
				},
			)
		},
	)
	return structs
}

func generateResetMethod(s structInfo, resettableTypes map[string]bool, fset *token.FileSet) string {
	receiver := receiverName(s.name, s.typ.Fields.List)
	typeParams := typeParamsString(s.params)

	var lines []string
	for _, field := range s.typ.Fields.List {
		for _, name := range fieldNames(field) {
			lines = append(lines, fieldReset(receiver+"."+name, field.Type, resettableTypes, fset, 0)...)
		}
	}

	var body strings.Builder
	for _, l := range lines {
		body.WriteString("\t")
		body.WriteString(l)
		body.WriteString("\n")
	}

	return fmt.Sprintf(
		"func (%s *%s%s) Reset() {\n\tif %s == nil {\n\t\treturn\n\t}\n%s}\n\n",
		receiver, s.name, typeParams, receiver, body.String(),
	)
}

func receiverName(structName string, fields []*ast.Field) string {
	first := "r"
	if len(structName) > 0 {
		first = strings.ToLower(structName[:1])
	}
	candidates := []string{first, "r", "rs", "rv"}

	fieldMap := make(map[string]bool)
	for _, f := range fields {
		for _, n := range f.Names {
			fieldMap[n.Name] = true
		}
		if f.Names == nil {
			fieldMap[embeddedFieldName(f.Type)] = true
		}
	}

	for _, c := range candidates {
		if c != "" && !fieldMap[c] {
			return c
		}
	}
	return "r"
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, len(field.Names))
		for i, n := range field.Names {
			names[i] = n.Name
		}
		return names
	}
	return []string{embeddedFieldName(field.Type)}
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	case *ast.SelectorExpr:
		return embeddedFieldName(t.X) + "." + t.Sel.Name
	}
	return ""
}

func resetNamedLike(
	expr string, typ ast.Expr, resettableTypes map[string]bool, fset *token.FileSet, indentStr string,
) []string {
	if ident, ok := typ.(*ast.Ident); ok && isBasicType(ident.Name) {
		return []string{indentStr + fmt.Sprintf("%s = %s", expr, zeroValueForBasic(ident.Name))}
	}
	base := baseNameForResettableCheck(typ)
	if base != "" && resettableTypes[base] {
		return []string{indentStr + fmt.Sprintf("%s.Reset()", expr)}
	}
	typeName := typeString(fset, typ)
	if typeName != "" {
		return []string{indentStr + fmt.Sprintf("%s = %s{}", expr, typeName)}
	}
	return nil
}

func fieldReset(expr string, typ ast.Expr, resettableTypes map[string]bool, fset *token.FileSet, indent int) []string {
	indentStr := strings.Repeat("\t", indent)

	switch t := typ.(type) {
	case *ast.Ident, *ast.SelectorExpr, *ast.IndexExpr, *ast.IndexListExpr:
		return resetNamedLike(expr, typ, resettableTypes, fset, indentStr)

	case *ast.ArrayType:
		if t.Len == nil {
			sliceExpr := expr
			if strings.HasPrefix(expr, "*") {
				sliceExpr = "(" + expr + ")"
			}
			return []string{indentStr + fmt.Sprintf("%s = %s[:0]", expr, sliceExpr)}
		}
		typeName := typeString(fset, typ)
		return []string{indentStr + fmt.Sprintf("%s = %s{}", expr, typeName)}

	case *ast.MapType:
		return []string{indentStr + fmt.Sprintf("clear(%s)", expr)}

	case *ast.StarExpr:
		if isResettableStruct(t.X, resettableTypes) {
			return []string{
				indentStr + fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok && %s != nil {", expr, expr),
				indentStr + "\tresetter.Reset()",
				indentStr + "}",
			}
		}
		innerLines := fieldReset("*"+expr, t.X, resettableTypes, fset, indent+1)
		lines := make([]string, 0, len(innerLines)+2)
		lines = append(lines, indentStr+fmt.Sprintf("if %s != nil {", expr))
		lines = append(lines, innerLines...)
		lines = append(lines, indentStr+"}")
		return lines

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return []string{indentStr + fmt.Sprintf("%s = nil", expr)}

	default:
		typeName := typeString(fset, typ)
		if typeName != "" {
			return []string{indentStr + fmt.Sprintf("%s = %s{}", expr, typeName)}
		}
		return nil
	}
}

func isResettableStruct(expr ast.Expr, resettableTypes map[string]bool) bool {
	base := baseNameForResettableCheck(expr)
	if base == "" {
		return false
	}
	return resettableTypes[base]
}

func isBasicType(name string) bool {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64",
		"complex64", "complex128",
		"string", "bool", "byte", "rune":
		return true
	}
	return false
}

func zeroValueForBasic(name string) string {
	switch name {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "complex64", "complex128":
		return "0"
	default:
		return "0"
	}
}

func typeString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, expr); err != nil {
		return ""
	}
	return strings.TrimSpace(buf.String())
}

func typeParamsString(params *ast.FieldList) string {
	if params == nil || len(params.List) == 0 {
		return ""
	}
	var names []string
	for _, field := range params.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}
	if len(names) == 0 {
		return ""
	}
	return "[" + strings.Join(names, ", ") + "]"
}

func baseNameForResettableCheck(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return baseNameForResettableCheck(t.X)
	case *ast.IndexExpr:
		return baseNameForResettableCheck(t.X)
	case *ast.IndexListExpr:
		return baseNameForResettableCheck(t.X)
	}
	return ""
}
