package main

import (
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProcessPackage(t *testing.T) {
	tests := []struct {
		name        string
		input       string
		wantFile    bool
		wantContent string
	}{
		{
			name: "no marker means no generation",
			input: `package sample

type Plain struct {
	x int
}
`,
			wantFile: false,
		},
		{
			name: "primitives",
			input: `package sample

// generate:reset
type Primitives struct {
	i int
	s string
	b bool
	f float64
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (p *Primitives) Reset() {
	if p == nil {
		return
	}
	p.i = 0
	p.s = ""
	p.b = false
	p.f = 0
}
`,
		},
		{
			name: "slice and map",
			input: `package sample

// generate:reset
type Collections struct {
	strings []string
	m       map[string]int
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (c *Collections) Reset() {
	if c == nil {
		return
	}
	c.strings = c.strings[:0]
	clear(c.m)
}
`,
		},
		{
			name: "pointer to primitive",
			input: `package sample

// generate:reset
type PtrPrimitives struct {
	iP *int
	sP *string
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (p *PtrPrimitives) Reset() {
	if p == nil {
		return
	}
	if p.iP != nil {
		*p.iP = 0
	}
	if p.sP != nil {
		*p.sP = ""
	}
}
`,
		},
		{
			name: "pointer to resettable struct uses interface check",
			input: `package sample

// generate:reset
type ResetableStruct struct {
	i     int
	child *ResetableStruct
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.i = 0
	if resetter, ok := r.child.(interface{ Reset() }); ok && r.child != nil {
		resetter.Reset()
	}
}
`,
		},
		{
			name: "pointer to non resettable struct",
			input: `package sample

type Plain struct {
	x int
}

// generate:reset
type WithPlainPtr struct {
	p *Plain
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (w *WithPlainPtr) Reset() {
	if w == nil {
		return
	}
	if w.p != nil {
		*w.p = Plain{}
	}
}
`,
		},
		{
			name: "value resettable struct calls Reset",
			input: `package sample

// generate:reset
type Inner struct {
	x int
}

// generate:reset
type Outer struct {
	inner Inner
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (i *Inner) Reset() {
	if i == nil {
		return
	}
	i.x = 0
}

func (o *Outer) Reset() {
	if o == nil {
		return
	}
	o.inner.Reset()
}
`,
		},
		{
			name: "arrays and pointers to collections",
			input: `package sample

// generate:reset
type Mixed struct {
	arr  [3]int
	arrP *[3]int
	sP   *[]string
	mP   *map[string]int
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (m *Mixed) Reset() {
	if m == nil {
		return
	}
	m.arr = [3]int{}
	if m.arrP != nil {
		*m.arrP = [3]int{}
	}
	if m.sP != nil {
		*m.sP = (*m.sP)[:0]
	}
	if m.mP != nil {
		clear(*m.mP)
	}
}
`,
		},
		{
			name: "embedded resettable struct",
			input: `package sample

// generate:reset
type Inner struct {
	x int
}

// generate:reset
type Container struct {
	Inner
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (c *Container) Reset() {
	if c == nil {
		return
	}
	c.Inner.Reset()
}

func (i *Inner) Reset() {
	if i == nil {
		return
	}
	i.x = 0
}
`,
		},
		{
			name: "generic struct",
			input: `package sample

// generate:reset
type Box[T any] struct {
	val   T
	items []T
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (b *Box[T]) Reset() {
	if b == nil {
		return
	}
	b.val = T{}
	b.items = b.items[:0]
}
`,
		},
		{
			name: "alias to resettable struct",
			input: `package sample

// generate:reset
type Inner struct {
	x int
}

// generate:reset
type InnerAlias = Inner

// generate:reset
type WithAlias struct {
	a InnerAlias
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (i *Inner) Reset() {
	if i == nil {
		return
	}
	i.x = 0
}

func (w *WithAlias) Reset() {
	if w == nil {
		return
	}
	w.a.Reset()
}
`,
		},
		{
			name: "alias to generic struct",
			input: `package sample

// generate:reset
type Box[T any] struct {
	x T
}

// generate:reset
type IntBox = Box[int]

// generate:reset
type WithIntBox struct {
	b IntBox
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (b *Box[T]) Reset() {
	if b == nil {
		return
	}
	b.x = T{}
}

func (w *WithIntBox) Reset() {
	if w == nil {
		return
	}
	w.b.Reset()
}
`,
		},
		{
			name: "generic instantiation field",
			input: `package sample

// generate:reset
type Box[T any] struct {
	x T
}

// generate:reset
type Wrapper struct {
	box Box[int]
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (b *Box[T]) Reset() {
	if b == nil {
		return
	}
	b.x = T{}
}

func (w *Wrapper) Reset() {
	if w == nil {
		return
	}
	w.box.Reset()
}
`,
		},
		{
			name: "alias to non resettable struct is not resettable",
			input: `package sample

type Plain struct {
	x int
}

// generate:reset
type PlainAlias = Plain

// generate:reset
type WithPlainAlias struct {
	p PlainAlias
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (w *WithPlainAlias) Reset() {
	if w == nil {
		return
	}
	w.p = PlainAlias{}
}
`,
		},
		{
			name: "embedded pointer to resettable struct",
			input: `package sample

// generate:reset
type Inner struct {
	x int
}

// generate:reset
type Container struct {
	*Inner
}
`,
			wantFile: true,
			wantContent: `// Code generated by reset tool; DO NOT EDIT.

package sample

func (c *Container) Reset() {
	if c == nil {
		return
	}
	if resetter, ok := c.Inner.(interface{ Reset() }); ok && c.Inner != nil {
		resetter.Reset()
	}
}

func (i *Inner) Reset() {
	if i == nil {
		return
	}
	i.x = 0
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				dir := t.TempDir()
				require.NoError(t, os.WriteFile(filepath.Join(dir, "input.go"), []byte(tt.input), 0o600))

				err := processPackage(dir)
				require.NoError(t, err)

				_, statErr := os.Stat(filepath.Join(dir, generatedFile))
				if !tt.wantFile {
					require.True(t, os.IsNotExist(statErr), "expected no generated file")
					return
				}
				require.NoError(t, statErr)

				got, err := fs.ReadFile(os.DirFS(dir), generatedFile)
				require.NoError(t, err)
				assert.Equal(t, tt.wantContent, string(got))
			},
		)
	}
}

func TestProcessPackage_NoGoFiles(t *testing.T) {
	dir := t.TempDir()
	err := processPackage(dir)
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(dir, generatedFile))
	require.True(t, os.IsNotExist(err), "expected no generated file in empty dir")
}
