// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package healthcheck

//go:generate minimock -i github.com/Dmitriy-Shcheklein/urlshortener/internal/handler/healthcheck.Service -o handler_mock_test.go -n ServiceMock -p healthcheck

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ServiceMock implements Service
type ServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPingDB          func() (err error)
	funcPingDBOrigin    string
	inspectFuncPingDB   func()
	afterPingDBCounter  uint64
	beforePingDBCounter uint64
	PingDBMock          mServiceMockPingDB
}

// NewServiceMock returns a mock for Service
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PingDBMock = mServiceMockPingDB{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mServiceMockPingDB struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockPingDBExpectation
	expectations       []*ServiceMockPingDBExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockPingDBExpectation specifies expectation struct of the Service.PingDB
type ServiceMockPingDBExpectation struct {
	mock *ServiceMock

	results      *ServiceMockPingDBResults
	returnOrigin string
	Counter      uint64
}

// ServiceMockPingDBResults contains results of the Service.PingDB
type ServiceMockPingDBResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPingDB *mServiceMockPingDB) Optional() *mServiceMockPingDB {
	mmPingDB.optional = true
	return mmPingDB
}

// Expect sets up expected params for Service.PingDB
func (mmPingDB *mServiceMockPingDB) Expect() *mServiceMockPingDB {
	if mmPingDB.mock.funcPingDB != nil {
		mmPingDB.mock.t.Fatalf("ServiceMock.PingDB mock is already set by Set")
	}

	if mmPingDB.defaultExpectation == nil {
		mmPingDB.defaultExpectation = &ServiceMockPingDBExpectation{}
	}

	return mmPingDB
}

// Inspect accepts an inspector function that has same arguments as the Service.PingDB
func (mmPingDB *mServiceMockPingDB) Inspect(f func()) *mServiceMockPingDB {
	if mmPingDB.mock.inspectFuncPingDB != nil {
		mmPingDB.mock.t.Fatalf("Inspect function is already set for ServiceMock.PingDB")
	}

	mmPingDB.mock.inspectFuncPingDB = f

	return mmPingDB
}

// Return sets up results that will be returned by Service.PingDB
func (mmPingDB *mServiceMockPingDB) Return(err error) *ServiceMock {
	if mmPingDB.mock.funcPingDB != nil {
		mmPingDB.mock.t.Fatalf("ServiceMock.PingDB mock is already set by Set")
	}

	if mmPingDB.defaultExpectation == nil {
		mmPingDB.defaultExpectation = &ServiceMockPingDBExpectation{mock: mmPingDB.mock}
	}
	mmPingDB.defaultExpectation.results = &ServiceMockPingDBResults{err}
	mmPingDB.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPingDB.mock
}

// Set uses given function f to mock the Service.PingDB method
func (mmPingDB *mServiceMockPingDB) Set(f func() (err error)) *ServiceMock {
	if mmPingDB.defaultExpectation != nil {
		mmPingDB.mock.t.Fatalf("Default expectation is already set for the Service.PingDB method")
	}

	if len(mmPingDB.expectations) > 0 {
		mmPingDB.mock.t.Fatalf("Some expectations are already set for the Service.PingDB method")
	}

	mmPingDB.mock.funcPingDB = f
	mmPingDB.mock.funcPingDBOrigin = minimock.CallerInfo(1)
	return mmPingDB.mock
}

// Times sets number of times Service.PingDB should be invoked
func (mmPingDB *mServiceMockPingDB) Times(n uint64) *mServiceMockPingDB {
	if n == 0 {
		mmPingDB.mock.t.Fatalf("Times of ServiceMock.PingDB mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPingDB.expectedInvocations, n)
	mmPingDB.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPingDB
}

func (mmPingDB *mServiceMockPingDB) invocationsDone() bool {
	if len(mmPingDB.expectations) == 0 && mmPingDB.defaultExpectation == nil && mmPingDB.mock.funcPingDB == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPingDB.mock.afterPingDBCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPingDB.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PingDB implements Service
func (mmPingDB *ServiceMock) PingDB() (err error) {
	mm_atomic.AddUint64(&mmPingDB.beforePingDBCounter, 1)
	defer mm_atomic.AddUint64(&mmPingDB.afterPingDBCounter, 1)

	mmPingDB.t.Helper()

	if mmPingDB.inspectFuncPingDB != nil {
		mmPingDB.inspectFuncPingDB()
	}

	if mmPingDB.PingDBMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPingDB.PingDBMock.defaultExpectation.Counter, 1)

		mm_results := mmPingDB.PingDBMock.defaultExpectation.results
		if mm_results == nil {
			mmPingDB.t.Fatal("No results are set for the ServiceMock.PingDB")
		}
		return (*mm_results).err
	}
	if mmPingDB.funcPingDB != nil {
		return mmPingDB.funcPingDB()
	}
	mmPingDB.t.Fatalf("Unexpected call to ServiceMock.PingDB.")
	return
}

// PingDBAfterCounter returns a count of finished ServiceMock.PingDB invocations
func (mmPingDB *ServiceMock) PingDBAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPingDB.afterPingDBCounter)
}

// PingDBBeforeCounter returns a count of ServiceMock.PingDB invocations
func (mmPingDB *ServiceMock) PingDBBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPingDB.beforePingDBCounter)
}

// MinimockPingDBDone returns true if the count of the PingDB invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockPingDBDone() bool {
	if m.PingDBMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingDBMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingDBMock.invocationsDone()
}

// MinimockPingDBInspect logs each unmet expectation
func (m *ServiceMock) MinimockPingDBInspect() {
	for _, e := range m.PingDBMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ServiceMock.PingDB")
		}
	}

	afterPingDBCounter := mm_atomic.LoadUint64(&m.afterPingDBCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingDBMock.defaultExpectation != nil && afterPingDBCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.PingDB at\n%s", m.PingDBMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPingDB != nil && afterPingDBCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.PingDB at\n%s", m.funcPingDBOrigin)
	}

	if !m.PingDBMock.invocationsDone() && afterPingDBCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.PingDB at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingDBMock.expectedInvocations), m.PingDBMock.expectedInvocationsOrigin, afterPingDBCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPingDBInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPingDBDone()
}
