// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shortener

import (
	"github.com/Dmitriy-Shcheklein/urlshortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkRepository creates a new instance of MockLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkRepository {
	mock := &MockLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkRepository is an autogenerated mock type for the LinkRepository type
type MockLinkRepository struct {
	mock.Mock
}

type MockLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkRepository) EXPECT() *MockLinkRepository_Expecter {
	return &MockLinkRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Delete(shortLinks []string, userID string) error {
	ret := _mock.Called(shortLinks, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, string) error); ok {
		r0 = returnFunc(shortLinks, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinkRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - shortLinks []string
//   - userID string
func (_e *MockLinkRepository_Expecter) Delete(shortLinks interface{}, userID interface{}) *MockLinkRepository_Delete_Call {
	return &MockLinkRepository_Delete_Call{Call: _e.mock.On("Delete", shortLinks, userID)}
}

func (_c *MockLinkRepository_Delete_Call) Run(run func(shortLinks []string, userID string)) *MockLinkRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Delete_Call) Return(err error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Delete_Call) RunAndReturn(run func(shortLinks []string, userID string) error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) FindByUserID(userID []byte) ([]model.LinkRow, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.LinkRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]model.LinkRow, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []model.LinkRow); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LinkRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockLinkRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - userID []byte
func (_e *MockLinkRepository_Expecter) FindByUserID(userID interface{}) *MockLinkRepository_FindByUserID_Call {
	return &MockLinkRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", userID)}
}

func (_c *MockLinkRepository_FindByUserID_Call) Run(run func(userID []byte)) *MockLinkRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_FindByUserID_Call) Return(linkRows []model.LinkRow, err error) *MockLinkRepository_FindByUserID_Call {
	_c.Call.Return(linkRows, err)
	return _c
}

func (_c *MockLinkRepository_FindByUserID_Call) RunAndReturn(run func(userID []byte) ([]model.LinkRow, error)) *MockLinkRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) GetByID(ID string) ([]byte, error) {
	ret := _mock.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(ID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLinkRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ID string
func (_e *MockLinkRepository_Expecter) GetByID(ID interface{}) *MockLinkRepository_GetByID_Call {
	return &MockLinkRepository_GetByID_Call{Call: _e.mock.On("GetByID", ID)}
}

func (_c *MockLinkRepository_GetByID_Call) Run(run func(ID string)) *MockLinkRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_GetByID_Call) Return(bytes []byte, err error) *MockLinkRepository_GetByID_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockLinkRepository_GetByID_Call) RunAndReturn(run func(ID string) ([]byte, error)) *MockLinkRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Save(path []byte, short []byte, userID []byte) error {
	ret := _mock.Called(path, short, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, []byte) error); ok {
		r0 = returnFunc(path, short, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - path []byte
//   - short []byte
//   - userID []byte
func (_e *MockLinkRepository_Expecter) Save(path interface{}, short interface{}, userID interface{}) *MockLinkRepository_Save_Call {
	return &MockLinkRepository_Save_Call{Call: _e.mock.On("Save", path, short, userID)}
}

func (_c *MockLinkRepository_Save_Call) Run(run func(path []byte, short []byte, userID []byte)) *MockLinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Save_Call) Return(err error) *MockLinkRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Save_Call) RunAndReturn(run func(path []byte, short []byte, userID []byte) error) *MockLinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) SaveMany(values []model.LinkRow, userID []byte) error {
	ret := _mock.Called(values, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]model.LinkRow, []byte) error); ok {
		r0 = returnFunc(values, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockLinkRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - values []model.LinkRow
//   - userID []byte
func (_e *MockLinkRepository_Expecter) SaveMany(values interface{}, userID interface{}) *MockLinkRepository_SaveMany_Call {
	return &MockLinkRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", values, userID)}
}

func (_c *MockLinkRepository_SaveMany_Call) Run(run func(values []model.LinkRow, userID []byte)) *MockLinkRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []model.LinkRow
		if args[0] != nil {
			arg0 = args[0].([]model.LinkRow)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_SaveMany_Call) Return(err error) *MockLinkRepository_SaveMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_SaveMany_Call) RunAndReturn(run func(values []model.LinkRow, userID []byte) error) *MockLinkRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}
