// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package healthcheck

//go:generate minimock -i github.com/Dmitriy-Shcheklein/urlshortener/internal/services/healthcheck.Repository -o healthcheck_mock_test.go -n RepositoryMock -p healthcheck

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements Repository
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPing          func() (err error)
	funcPingOrigin    string
	inspectFuncPing   func()
	afterPingCounter  uint64
	beforePingCounter uint64
	PingMock          mRepositoryMockPing
}

// NewRepositoryMock returns a mock for Repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PingMock = mRepositoryMockPing{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockPing struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockPingExpectation
	expectations       []*RepositoryMockPingExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockPingExpectation specifies expectation struct of the Repository.Ping
type RepositoryMockPingExpectation struct {
	mock *RepositoryMock

	results      *RepositoryMockPingResults
	returnOrigin string
	Counter      uint64
}

// RepositoryMockPingResults contains results of the Repository.Ping
type RepositoryMockPingResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPing *mRepositoryMockPing) Optional() *mRepositoryMockPing {
	mmPing.optional = true
	return mmPing
}

// Expect sets up expected params for Repository.Ping
func (mmPing *mRepositoryMockPing) Expect() *mRepositoryMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("RepositoryMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &RepositoryMockPingExpectation{}
	}

	return mmPing
}

// Inspect accepts an inspector function that has same arguments as the Repository.Ping
func (mmPing *mRepositoryMockPing) Inspect(f func()) *mRepositoryMockPing {
	if mmPing.mock.inspectFuncPing != nil {
		mmPing.mock.t.Fatalf("Inspect function is already set for RepositoryMock.Ping")
	}

	mmPing.mock.inspectFuncPing = f

	return mmPing
}

// Return sets up results that will be returned by Repository.Ping
func (mmPing *mRepositoryMockPing) Return(err error) *RepositoryMock {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("RepositoryMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &RepositoryMockPingExpectation{mock: mmPing.mock}
	}
	mmPing.defaultExpectation.results = &RepositoryMockPingResults{err}
	mmPing.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Set uses given function f to mock the Repository.Ping method
func (mmPing *mRepositoryMockPing) Set(f func() (err error)) *RepositoryMock {
	if mmPing.defaultExpectation != nil {
		mmPing.mock.t.Fatalf("Default expectation is already set for the Repository.Ping method")
	}

	if len(mmPing.expectations) > 0 {
		mmPing.mock.t.Fatalf("Some expectations are already set for the Repository.Ping method")
	}

	mmPing.mock.funcPing = f
	mmPing.mock.funcPingOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Times sets number of times Repository.Ping should be invoked
func (mmPing *mRepositoryMockPing) Times(n uint64) *mRepositoryMockPing {
	if n == 0 {
		mmPing.mock.t.Fatalf("Times of RepositoryMock.Ping mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPing.expectedInvocations, n)
	mmPing.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPing
}

func (mmPing *mRepositoryMockPing) invocationsDone() bool {
	if len(mmPing.expectations) == 0 && mmPing.defaultExpectation == nil && mmPing.mock.funcPing == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPing.mock.afterPingCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPing.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Ping implements Repository
func (mmPing *RepositoryMock) Ping() (err error) {
	mm_atomic.AddUint64(&mmPing.beforePingCounter, 1)
	defer mm_atomic.AddUint64(&mmPing.afterPingCounter, 1)

	mmPing.t.Helper()

	if mmPing.inspectFuncPing != nil {
		mmPing.inspectFuncPing()
	}

	if mmPing.PingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPing.PingMock.defaultExpectation.Counter, 1)

		mm_results := mmPing.PingMock.defaultExpectation.results
		if mm_results == nil {
			mmPing.t.Fatal("No results are set for the RepositoryMock.Ping")
		}
		return (*mm_results).err
	}
	if mmPing.funcPing != nil {
		return mmPing.funcPing()
	}
	mmPing.t.Fatalf("Unexpected call to RepositoryMock.Ping.")
	return
}

// PingAfterCounter returns a count of finished RepositoryMock.Ping invocations
func (mmPing *RepositoryMock) PingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.afterPingCounter)
}

// PingBeforeCounter returns a count of RepositoryMock.Ping invocations
func (mmPing *RepositoryMock) PingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.beforePingCounter)
}

// MinimockPingDone returns true if the count of the Ping invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockPingDone() bool {
	if m.PingMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingMock.invocationsDone()
}

// MinimockPingInspect logs each unmet expectation
func (m *RepositoryMock) MinimockPingInspect() {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepositoryMock.Ping")
		}
	}

	afterPingCounter := mm_atomic.LoadUint64(&m.afterPingCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.Ping at\n%s", m.PingMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.Ping at\n%s", m.funcPingOrigin)
	}

	if !m.PingMock.invocationsDone() && afterPingCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.Ping at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingMock.expectedInvocations), m.PingMock.expectedInvocationsOrigin, afterPingCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPingInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPingDone()
}
