// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middlewares

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// GetSalt provides a mock function for the type MockConfig
func (_mock *MockConfig) GetSalt() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSalt")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockConfig_GetSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalt'
type MockConfig_GetSalt_Call struct {
	*mock.Call
}

// GetSalt is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetSalt() *MockConfig_GetSalt_Call {
	return &MockConfig_GetSalt_Call{Call: _e.mock.On("GetSalt")}
}

func (_c *MockConfig_GetSalt_Call) Run(run func()) *MockConfig_GetSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetSalt_Call) Return(bytes []byte) *MockConfig_GetSalt_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockConfig_GetSalt_Call) RunAndReturn(run func() []byte) *MockConfig_GetSalt_Call {
	_c.Call.Return(run)
	return _c
}
