// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPgxRow creates a new instance of MockPgxRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPgxRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPgxRow {
	mock := &MockPgxRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPgxRow is an autogenerated mock type for the PgxRow type
type MockPgxRow struct {
	mock.Mock
}

type MockPgxRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPgxRow) EXPECT() *MockPgxRow_Expecter {
	return &MockPgxRow_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockPgxRow
func (_mock *MockPgxRow) Scan(dest ...any) error {
	var tmpRet mock.Arguments
	if len(dest) > 0 {
		tmpRet = _mock.Called(dest)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(dest...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPgxRow_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockPgxRow_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockPgxRow_Expecter) Scan(dest ...interface{}) *MockPgxRow_Scan_Call {
	return &MockPgxRow_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockPgxRow_Scan_Call) Run(run func(dest ...any)) *MockPgxRow_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockPgxRow_Scan_Call) Return(err error) *MockPgxRow_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPgxRow_Scan_Call) RunAndReturn(run func(dest ...any) error) *MockPgxRow_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockPool
func (_mock *MockPool) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Exec_Call {
	return &MockPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPool_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockPool_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockPool_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)) *MockPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockPool
func (_mock *MockPool) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockPool_Expecter) Ping() *MockPool_Ping_Call {
	return &MockPool_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockPool_Ping_Call) Run(run func()) *MockPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Ping_Call) Return(err error) *MockPool_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPool_Ping_Call) RunAndReturn(run func() error) *MockPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockPool
func (_mock *MockPool) QueryRow(ctx context.Context, sql string, args ...any) PgxRow {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 PgxRow
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) PgxRow); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PgxRow)
		}
	}
	return r0
}

// MockPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_QueryRow_Call {
	return &MockPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPool_QueryRow_Call) Return(v PgxRow) *MockPool_QueryRow_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPool_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) PgxRow) *MockPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
