// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPgxRow creates a new instance of MockPgxRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPgxRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPgxRow {
	mock := &MockPgxRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPgxRow is an autogenerated mock type for the PgxRow type
type MockPgxRow struct {
	mock.Mock
}

type MockPgxRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPgxRow) EXPECT() *MockPgxRow_Expecter {
	return &MockPgxRow_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockPgxRow
func (_mock *MockPgxRow) Scan(dest ...any) error {
	var tmpRet mock.Arguments
	if len(dest) > 0 {
		tmpRet = _mock.Called(dest)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(dest...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPgxRow_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockPgxRow_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockPgxRow_Expecter) Scan(dest ...interface{}) *MockPgxRow_Scan_Call {
	return &MockPgxRow_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockPgxRow_Scan_Call) Run(run func(dest ...any)) *MockPgxRow_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockPgxRow_Scan_Call) Return(err error) *MockPgxRow_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPgxRow_Scan_Call) RunAndReturn(run func(dest ...any) error) *MockPgxRow_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPgxRows creates a new instance of MockPgxRows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPgxRows(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPgxRows {
	mock := &MockPgxRows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPgxRows is an autogenerated mock type for the PgxRows type
type MockPgxRows struct {
	mock.Mock
}

type MockPgxRows_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPgxRows) EXPECT() *MockPgxRows_Expecter {
	return &MockPgxRows_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Close() {
	_mock.Called()
	return
}

// MockPgxRows_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPgxRows_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) Close() *MockPgxRows_Close_Call {
	return &MockPgxRows_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPgxRows_Close_Call) Run(run func()) *MockPgxRows_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_Close_Call) Return() *MockPgxRows_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPgxRows_Close_Call) RunAndReturn(run func()) *MockPgxRows_Close_Call {
	_c.Run(run)
	return _c
}

// CommandTag provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) CommandTag() pgconn.CommandTag {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandTag")
	}

	var r0 pgconn.CommandTag
	if returnFunc, ok := ret.Get(0).(func() pgconn.CommandTag); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	return r0
}

// MockPgxRows_CommandTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandTag'
type MockPgxRows_CommandTag_Call struct {
	*mock.Call
}

// CommandTag is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) CommandTag() *MockPgxRows_CommandTag_Call {
	return &MockPgxRows_CommandTag_Call{Call: _e.mock.On("CommandTag")}
}

func (_c *MockPgxRows_CommandTag_Call) Run(run func()) *MockPgxRows_CommandTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_CommandTag_Call) Return(commandTag pgconn.CommandTag) *MockPgxRows_CommandTag_Call {
	_c.Call.Return(commandTag)
	return _c
}

func (_c *MockPgxRows_CommandTag_Call) RunAndReturn(run func() pgconn.CommandTag) *MockPgxRows_CommandTag_Call {
	_c.Call.Return(run)
	return _c
}

// Conn provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Conn() *pgx.Conn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Conn")
	}

	var r0 *pgx.Conn
	if returnFunc, ok := ret.Get(0).(func() *pgx.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgx.Conn)
		}
	}
	return r0
}

// MockPgxRows_Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conn'
type MockPgxRows_Conn_Call struct {
	*mock.Call
}

// Conn is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) Conn() *MockPgxRows_Conn_Call {
	return &MockPgxRows_Conn_Call{Call: _e.mock.On("Conn")}
}

func (_c *MockPgxRows_Conn_Call) Run(run func()) *MockPgxRows_Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_Conn_Call) Return(conn *pgx.Conn) *MockPgxRows_Conn_Call {
	_c.Call.Return(conn)
	return _c
}

func (_c *MockPgxRows_Conn_Call) RunAndReturn(run func() *pgx.Conn) *MockPgxRows_Conn_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPgxRows_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockPgxRows_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) Err() *MockPgxRows_Err_Call {
	return &MockPgxRows_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockPgxRows_Err_Call) Run(run func()) *MockPgxRows_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_Err_Call) Return(err error) *MockPgxRows_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPgxRows_Err_Call) RunAndReturn(run func() error) *MockPgxRows_Err_Call {
	_c.Call.Return(run)
	return _c
}

// FieldDescriptions provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) FieldDescriptions() []pgconn.FieldDescription {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FieldDescriptions")
	}

	var r0 []pgconn.FieldDescription
	if returnFunc, ok := ret.Get(0).(func() []pgconn.FieldDescription); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgconn.FieldDescription)
		}
	}
	return r0
}

// MockPgxRows_FieldDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldDescriptions'
type MockPgxRows_FieldDescriptions_Call struct {
	*mock.Call
}

// FieldDescriptions is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) FieldDescriptions() *MockPgxRows_FieldDescriptions_Call {
	return &MockPgxRows_FieldDescriptions_Call{Call: _e.mock.On("FieldDescriptions")}
}

func (_c *MockPgxRows_FieldDescriptions_Call) Run(run func()) *MockPgxRows_FieldDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_FieldDescriptions_Call) Return(fieldDescriptions []pgconn.FieldDescription) *MockPgxRows_FieldDescriptions_Call {
	_c.Call.Return(fieldDescriptions)
	return _c
}

func (_c *MockPgxRows_FieldDescriptions_Call) RunAndReturn(run func() []pgconn.FieldDescription) *MockPgxRows_FieldDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Next() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPgxRows_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockPgxRows_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) Next() *MockPgxRows_Next_Call {
	return &MockPgxRows_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockPgxRows_Next_Call) Run(run func()) *MockPgxRows_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_Next_Call) Return(b bool) *MockPgxRows_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPgxRows_Next_Call) RunAndReturn(run func() bool) *MockPgxRows_Next_Call {
	_c.Call.Return(run)
	return _c
}

// RawValues provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) RawValues() [][]byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RawValues")
	}

	var r0 [][]byte
	if returnFunc, ok := ret.Get(0).(func() [][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	return r0
}

// MockPgxRows_RawValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawValues'
type MockPgxRows_RawValues_Call struct {
	*mock.Call
}

// RawValues is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) RawValues() *MockPgxRows_RawValues_Call {
	return &MockPgxRows_RawValues_Call{Call: _e.mock.On("RawValues")}
}

func (_c *MockPgxRows_RawValues_Call) Run(run func()) *MockPgxRows_RawValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_RawValues_Call) Return(bytess [][]byte) *MockPgxRows_RawValues_Call {
	_c.Call.Return(bytess)
	return _c
}

func (_c *MockPgxRows_RawValues_Call) RunAndReturn(run func() [][]byte) *MockPgxRows_RawValues_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Scan(dest ...any) error {
	var tmpRet mock.Arguments
	if len(dest) > 0 {
		tmpRet = _mock.Called(dest)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(dest...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPgxRows_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockPgxRows_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockPgxRows_Expecter) Scan(dest ...interface{}) *MockPgxRows_Scan_Call {
	return &MockPgxRows_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockPgxRows_Scan_Call) Run(run func(dest ...any)) *MockPgxRows_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockPgxRows_Scan_Call) Return(err error) *MockPgxRows_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPgxRows_Scan_Call) RunAndReturn(run func(dest ...any) error) *MockPgxRows_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function for the type MockPgxRows
func (_mock *MockPgxRows) Values() ([]any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPgxRows_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type MockPgxRows_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *MockPgxRows_Expecter) Values() *MockPgxRows_Values_Call {
	return &MockPgxRows_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *MockPgxRows_Values_Call) Run(run func()) *MockPgxRows_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPgxRows_Values_Call) Return(vs []any, err error) *MockPgxRows_Values_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockPgxRows_Values_Call) RunAndReturn(run func() ([]any, error)) *MockPgxRows_Values_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockPool
func (_mock *MockPool) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Exec_Call {
	return &MockPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPool_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockPool_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockPool_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)) *MockPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockPool
func (_mock *MockPool) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockPool_Expecter) Ping() *MockPool_Ping_Call {
	return &MockPool_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockPool_Ping_Call) Run(run func()) *MockPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_Ping_Call) Return(err error) *MockPool_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPool_Ping_Call) RunAndReturn(run func() error) *MockPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockPool
func (_mock *MockPool) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_Query_Call {
	return &MockPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPool_Query_Call) Return(rows pgx.Rows, err error) *MockPool_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockPool_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *MockPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockPool
func (_mock *MockPool) QueryRow(ctx context.Context, sql string, args ...any) PgxRow {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 PgxRow
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) PgxRow); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PgxRow)
		}
	}
	return r0
}

// MockPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockPool_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockPool_QueryRow_Call {
	return &MockPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPool_QueryRow_Call) Return(v PgxRow) *MockPool_QueryRow_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPool_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) PgxRow) *MockPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
