// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package postgres

//go:generate minimock -i github.com/Dmitriy-Shcheklein/urlshortener/internal/repository/postgres.Pool -o repository_mock_test.go -n PoolMock -p postgres

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// PoolMock implements Pool
type PoolMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcExec          func(ctx context.Context, sql string, args ...any) (c2 pgconn.CommandTag, err error)
	funcExecOrigin    string
	inspectFuncExec   func(ctx context.Context, sql string, args ...any)
	afterExecCounter  uint64
	beforeExecCounter uint64
	ExecMock          mPoolMockExec

	funcPing          func() (err error)
	funcPingOrigin    string
	inspectFuncPing   func()
	afterPingCounter  uint64
	beforePingCounter uint64
	PingMock          mPoolMockPing

	funcQueryRow          func(ctx context.Context, sql string, args ...any) (r1 pgx.Row)
	funcQueryRowOrigin    string
	inspectFuncQueryRow   func(ctx context.Context, sql string, args ...any)
	afterQueryRowCounter  uint64
	beforeQueryRowCounter uint64
	QueryRowMock          mPoolMockQueryRow
}

// NewPoolMock returns a mock for Pool
func NewPoolMock(t minimock.Tester) *PoolMock {
	m := &PoolMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ExecMock = mPoolMockExec{mock: m}
	m.ExecMock.callArgs = []*PoolMockExecParams{}

	m.PingMock = mPoolMockPing{mock: m}

	m.QueryRowMock = mPoolMockQueryRow{mock: m}
	m.QueryRowMock.callArgs = []*PoolMockQueryRowParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPoolMockExec struct {
	optional           bool
	mock               *PoolMock
	defaultExpectation *PoolMockExecExpectation
	expectations       []*PoolMockExecExpectation

	callArgs []*PoolMockExecParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PoolMockExecExpectation specifies expectation struct of the Pool.Exec
type PoolMockExecExpectation struct {
	mock               *PoolMock
	params             *PoolMockExecParams
	paramPtrs          *PoolMockExecParamPtrs
	expectationOrigins PoolMockExecExpectationOrigins
	results            *PoolMockExecResults
	returnOrigin       string
	Counter            uint64
}

// PoolMockExecParams contains parameters of the Pool.Exec
type PoolMockExecParams struct {
	ctx  context.Context
	sql  string
	args []any
}

// PoolMockExecParamPtrs contains pointers to parameters of the Pool.Exec
type PoolMockExecParamPtrs struct {
	ctx  *context.Context
	sql  *string
	args *[]any
}

// PoolMockExecResults contains results of the Pool.Exec
type PoolMockExecResults struct {
	c2  pgconn.CommandTag
	err error
}

// PoolMockExecOrigins contains origins of expectations of the Pool.Exec
type PoolMockExecExpectationOrigins struct {
	origin     string
	originCtx  string
	originSql  string
	originArgs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmExec *mPoolMockExec) Optional() *mPoolMockExec {
	mmExec.optional = true
	return mmExec
}

// Expect sets up expected params for Pool.Exec
func (mmExec *mPoolMockExec) Expect(ctx context.Context, sql string, args ...any) *mPoolMockExec {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	if mmExec.defaultExpectation == nil {
		mmExec.defaultExpectation = &PoolMockExecExpectation{}
	}

	if mmExec.defaultExpectation.paramPtrs != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by ExpectParams functions")
	}

	mmExec.defaultExpectation.params = &PoolMockExecParams{ctx, sql, args}
	mmExec.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmExec.expectations {
		if minimock.Equal(e.params, mmExec.defaultExpectation.params) {
			mmExec.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmExec.defaultExpectation.params)
		}
	}

	return mmExec
}

// ExpectCtxParam1 sets up expected param ctx for Pool.Exec
func (mmExec *mPoolMockExec) ExpectCtxParam1(ctx context.Context) *mPoolMockExec {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	if mmExec.defaultExpectation == nil {
		mmExec.defaultExpectation = &PoolMockExecExpectation{}
	}

	if mmExec.defaultExpectation.params != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Expect")
	}

	if mmExec.defaultExpectation.paramPtrs == nil {
		mmExec.defaultExpectation.paramPtrs = &PoolMockExecParamPtrs{}
	}
	mmExec.defaultExpectation.paramPtrs.ctx = &ctx
	mmExec.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmExec
}

// ExpectSqlParam2 sets up expected param sql for Pool.Exec
func (mmExec *mPoolMockExec) ExpectSqlParam2(sql string) *mPoolMockExec {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	if mmExec.defaultExpectation == nil {
		mmExec.defaultExpectation = &PoolMockExecExpectation{}
	}

	if mmExec.defaultExpectation.params != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Expect")
	}

	if mmExec.defaultExpectation.paramPtrs == nil {
		mmExec.defaultExpectation.paramPtrs = &PoolMockExecParamPtrs{}
	}
	mmExec.defaultExpectation.paramPtrs.sql = &sql
	mmExec.defaultExpectation.expectationOrigins.originSql = minimock.CallerInfo(1)

	return mmExec
}

// ExpectArgsParam3 sets up expected param args for Pool.Exec
func (mmExec *mPoolMockExec) ExpectArgsParam3(args ...any) *mPoolMockExec {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	if mmExec.defaultExpectation == nil {
		mmExec.defaultExpectation = &PoolMockExecExpectation{}
	}

	if mmExec.defaultExpectation.params != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Expect")
	}

	if mmExec.defaultExpectation.paramPtrs == nil {
		mmExec.defaultExpectation.paramPtrs = &PoolMockExecParamPtrs{}
	}
	mmExec.defaultExpectation.paramPtrs.args = &args
	mmExec.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmExec
}

// Inspect accepts an inspector function that has same arguments as the Pool.Exec
func (mmExec *mPoolMockExec) Inspect(f func(ctx context.Context, sql string, args ...any)) *mPoolMockExec {
	if mmExec.mock.inspectFuncExec != nil {
		mmExec.mock.t.Fatalf("Inspect function is already set for PoolMock.Exec")
	}

	mmExec.mock.inspectFuncExec = f

	return mmExec
}

// Return sets up results that will be returned by Pool.Exec
func (mmExec *mPoolMockExec) Return(c2 pgconn.CommandTag, err error) *PoolMock {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	if mmExec.defaultExpectation == nil {
		mmExec.defaultExpectation = &PoolMockExecExpectation{mock: mmExec.mock}
	}
	mmExec.defaultExpectation.results = &PoolMockExecResults{c2, err}
	mmExec.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmExec.mock
}

// Set uses given function f to mock the Pool.Exec method
func (mmExec *mPoolMockExec) Set(f func(ctx context.Context, sql string, args ...any) (c2 pgconn.CommandTag, err error)) *PoolMock {
	if mmExec.defaultExpectation != nil {
		mmExec.mock.t.Fatalf("Default expectation is already set for the Pool.Exec method")
	}

	if len(mmExec.expectations) > 0 {
		mmExec.mock.t.Fatalf("Some expectations are already set for the Pool.Exec method")
	}

	mmExec.mock.funcExec = f
	mmExec.mock.funcExecOrigin = minimock.CallerInfo(1)
	return mmExec.mock
}

// When sets expectation for the Pool.Exec which will trigger the result defined by the following
// Then helper
func (mmExec *mPoolMockExec) When(ctx context.Context, sql string, args ...any) *PoolMockExecExpectation {
	if mmExec.mock.funcExec != nil {
		mmExec.mock.t.Fatalf("PoolMock.Exec mock is already set by Set")
	}

	expectation := &PoolMockExecExpectation{
		mock:               mmExec.mock,
		params:             &PoolMockExecParams{ctx, sql, args},
		expectationOrigins: PoolMockExecExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmExec.expectations = append(mmExec.expectations, expectation)
	return expectation
}

// Then sets up Pool.Exec return parameters for the expectation previously defined by the When method
func (e *PoolMockExecExpectation) Then(c2 pgconn.CommandTag, err error) *PoolMock {
	e.results = &PoolMockExecResults{c2, err}
	return e.mock
}

// Times sets number of times Pool.Exec should be invoked
func (mmExec *mPoolMockExec) Times(n uint64) *mPoolMockExec {
	if n == 0 {
		mmExec.mock.t.Fatalf("Times of PoolMock.Exec mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmExec.expectedInvocations, n)
	mmExec.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmExec
}

func (mmExec *mPoolMockExec) invocationsDone() bool {
	if len(mmExec.expectations) == 0 && mmExec.defaultExpectation == nil && mmExec.mock.funcExec == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmExec.mock.afterExecCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmExec.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Exec implements Pool
func (mmExec *PoolMock) Exec(ctx context.Context, sql string, args ...any) (c2 pgconn.CommandTag, err error) {
	mm_atomic.AddUint64(&mmExec.beforeExecCounter, 1)
	defer mm_atomic.AddUint64(&mmExec.afterExecCounter, 1)

	mmExec.t.Helper()

	if mmExec.inspectFuncExec != nil {
		mmExec.inspectFuncExec(ctx, sql, args...)
	}

	mm_params := PoolMockExecParams{ctx, sql, args}

	// Record call args
	mmExec.ExecMock.mutex.Lock()
	mmExec.ExecMock.callArgs = append(mmExec.ExecMock.callArgs, &mm_params)
	mmExec.ExecMock.mutex.Unlock()

	for _, e := range mmExec.ExecMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmExec.ExecMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmExec.ExecMock.defaultExpectation.Counter, 1)
		mm_want := mmExec.ExecMock.defaultExpectation.params
		mm_want_ptrs := mmExec.ExecMock.defaultExpectation.paramPtrs

		mm_got := PoolMockExecParams{ctx, sql, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmExec.t.Errorf("PoolMock.Exec got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExec.ExecMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sql != nil && !minimock.Equal(*mm_want_ptrs.sql, mm_got.sql) {
				mmExec.t.Errorf("PoolMock.Exec got unexpected parameter sql, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExec.ExecMock.defaultExpectation.expectationOrigins.originSql, *mm_want_ptrs.sql, mm_got.sql, minimock.Diff(*mm_want_ptrs.sql, mm_got.sql))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmExec.t.Errorf("PoolMock.Exec got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExec.ExecMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmExec.t.Errorf("PoolMock.Exec got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmExec.ExecMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmExec.ExecMock.defaultExpectation.results
		if mm_results == nil {
			mmExec.t.Fatal("No results are set for the PoolMock.Exec")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmExec.funcExec != nil {
		return mmExec.funcExec(ctx, sql, args...)
	}
	mmExec.t.Fatalf("Unexpected call to PoolMock.Exec. %v %v %v", ctx, sql, args)
	return
}

// ExecAfterCounter returns a count of finished PoolMock.Exec invocations
func (mmExec *PoolMock) ExecAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExec.afterExecCounter)
}

// ExecBeforeCounter returns a count of PoolMock.Exec invocations
func (mmExec *PoolMock) ExecBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExec.beforeExecCounter)
}

// Calls returns a list of arguments used in each call to PoolMock.Exec.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmExec *mPoolMockExec) Calls() []*PoolMockExecParams {
	mmExec.mutex.RLock()

	argCopy := make([]*PoolMockExecParams, len(mmExec.callArgs))
	copy(argCopy, mmExec.callArgs)

	mmExec.mutex.RUnlock()

	return argCopy
}

// MinimockExecDone returns true if the count of the Exec invocations corresponds
// the number of defined expectations
func (m *PoolMock) MinimockExecDone() bool {
	if m.ExecMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ExecMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ExecMock.invocationsDone()
}

// MinimockExecInspect logs each unmet expectation
func (m *PoolMock) MinimockExecInspect() {
	for _, e := range m.ExecMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PoolMock.Exec at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterExecCounter := mm_atomic.LoadUint64(&m.afterExecCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ExecMock.defaultExpectation != nil && afterExecCounter < 1 {
		if m.ExecMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PoolMock.Exec at\n%s", m.ExecMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PoolMock.Exec at\n%s with params: %#v", m.ExecMock.defaultExpectation.expectationOrigins.origin, *m.ExecMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcExec != nil && afterExecCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.Exec at\n%s", m.funcExecOrigin)
	}

	if !m.ExecMock.invocationsDone() && afterExecCounter > 0 {
		m.t.Errorf("Expected %d calls to PoolMock.Exec at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ExecMock.expectedInvocations), m.ExecMock.expectedInvocationsOrigin, afterExecCounter)
	}
}

type mPoolMockPing struct {
	optional           bool
	mock               *PoolMock
	defaultExpectation *PoolMockPingExpectation
	expectations       []*PoolMockPingExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PoolMockPingExpectation specifies expectation struct of the Pool.Ping
type PoolMockPingExpectation struct {
	mock *PoolMock

	results      *PoolMockPingResults
	returnOrigin string
	Counter      uint64
}

// PoolMockPingResults contains results of the Pool.Ping
type PoolMockPingResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPing *mPoolMockPing) Optional() *mPoolMockPing {
	mmPing.optional = true
	return mmPing
}

// Expect sets up expected params for Pool.Ping
func (mmPing *mPoolMockPing) Expect() *mPoolMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("PoolMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &PoolMockPingExpectation{}
	}

	return mmPing
}

// Inspect accepts an inspector function that has same arguments as the Pool.Ping
func (mmPing *mPoolMockPing) Inspect(f func()) *mPoolMockPing {
	if mmPing.mock.inspectFuncPing != nil {
		mmPing.mock.t.Fatalf("Inspect function is already set for PoolMock.Ping")
	}

	mmPing.mock.inspectFuncPing = f

	return mmPing
}

// Return sets up results that will be returned by Pool.Ping
func (mmPing *mPoolMockPing) Return(err error) *PoolMock {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("PoolMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &PoolMockPingExpectation{mock: mmPing.mock}
	}
	mmPing.defaultExpectation.results = &PoolMockPingResults{err}
	mmPing.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Set uses given function f to mock the Pool.Ping method
func (mmPing *mPoolMockPing) Set(f func() (err error)) *PoolMock {
	if mmPing.defaultExpectation != nil {
		mmPing.mock.t.Fatalf("Default expectation is already set for the Pool.Ping method")
	}

	if len(mmPing.expectations) > 0 {
		mmPing.mock.t.Fatalf("Some expectations are already set for the Pool.Ping method")
	}

	mmPing.mock.funcPing = f
	mmPing.mock.funcPingOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Times sets number of times Pool.Ping should be invoked
func (mmPing *mPoolMockPing) Times(n uint64) *mPoolMockPing {
	if n == 0 {
		mmPing.mock.t.Fatalf("Times of PoolMock.Ping mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPing.expectedInvocations, n)
	mmPing.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPing
}

func (mmPing *mPoolMockPing) invocationsDone() bool {
	if len(mmPing.expectations) == 0 && mmPing.defaultExpectation == nil && mmPing.mock.funcPing == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPing.mock.afterPingCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPing.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Ping implements Pool
func (mmPing *PoolMock) Ping() (err error) {
	mm_atomic.AddUint64(&mmPing.beforePingCounter, 1)
	defer mm_atomic.AddUint64(&mmPing.afterPingCounter, 1)

	mmPing.t.Helper()

	if mmPing.inspectFuncPing != nil {
		mmPing.inspectFuncPing()
	}

	if mmPing.PingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPing.PingMock.defaultExpectation.Counter, 1)

		mm_results := mmPing.PingMock.defaultExpectation.results
		if mm_results == nil {
			mmPing.t.Fatal("No results are set for the PoolMock.Ping")
		}
		return (*mm_results).err
	}
	if mmPing.funcPing != nil {
		return mmPing.funcPing()
	}
	mmPing.t.Fatalf("Unexpected call to PoolMock.Ping.")
	return
}

// PingAfterCounter returns a count of finished PoolMock.Ping invocations
func (mmPing *PoolMock) PingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.afterPingCounter)
}

// PingBeforeCounter returns a count of PoolMock.Ping invocations
func (mmPing *PoolMock) PingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.beforePingCounter)
}

// MinimockPingDone returns true if the count of the Ping invocations corresponds
// the number of defined expectations
func (m *PoolMock) MinimockPingDone() bool {
	if m.PingMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingMock.invocationsDone()
}

// MinimockPingInspect logs each unmet expectation
func (m *PoolMock) MinimockPingInspect() {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to PoolMock.Ping")
		}
	}

	afterPingCounter := mm_atomic.LoadUint64(&m.afterPingCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.Ping at\n%s", m.PingMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.Ping at\n%s", m.funcPingOrigin)
	}

	if !m.PingMock.invocationsDone() && afterPingCounter > 0 {
		m.t.Errorf("Expected %d calls to PoolMock.Ping at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingMock.expectedInvocations), m.PingMock.expectedInvocationsOrigin, afterPingCounter)
	}
}

type mPoolMockQueryRow struct {
	optional           bool
	mock               *PoolMock
	defaultExpectation *PoolMockQueryRowExpectation
	expectations       []*PoolMockQueryRowExpectation

	callArgs []*PoolMockQueryRowParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PoolMockQueryRowExpectation specifies expectation struct of the Pool.QueryRow
type PoolMockQueryRowExpectation struct {
	mock               *PoolMock
	params             *PoolMockQueryRowParams
	paramPtrs          *PoolMockQueryRowParamPtrs
	expectationOrigins PoolMockQueryRowExpectationOrigins
	results            *PoolMockQueryRowResults
	returnOrigin       string
	Counter            uint64
}

// PoolMockQueryRowParams contains parameters of the Pool.QueryRow
type PoolMockQueryRowParams struct {
	ctx  context.Context
	sql  string
	args []any
}

// PoolMockQueryRowParamPtrs contains pointers to parameters of the Pool.QueryRow
type PoolMockQueryRowParamPtrs struct {
	ctx  *context.Context
	sql  *string
	args *[]any
}

// PoolMockQueryRowResults contains results of the Pool.QueryRow
type PoolMockQueryRowResults struct {
	r1 pgx.Row
}

// PoolMockQueryRowOrigins contains origins of expectations of the Pool.QueryRow
type PoolMockQueryRowExpectationOrigins struct {
	origin     string
	originCtx  string
	originSql  string
	originArgs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmQueryRow *mPoolMockQueryRow) Optional() *mPoolMockQueryRow {
	mmQueryRow.optional = true
	return mmQueryRow
}

// Expect sets up expected params for Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) Expect(ctx context.Context, sql string, args ...any) *mPoolMockQueryRow {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	if mmQueryRow.defaultExpectation == nil {
		mmQueryRow.defaultExpectation = &PoolMockQueryRowExpectation{}
	}

	if mmQueryRow.defaultExpectation.paramPtrs != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by ExpectParams functions")
	}

	mmQueryRow.defaultExpectation.params = &PoolMockQueryRowParams{ctx, sql, args}
	mmQueryRow.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmQueryRow.expectations {
		if minimock.Equal(e.params, mmQueryRow.defaultExpectation.params) {
			mmQueryRow.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmQueryRow.defaultExpectation.params)
		}
	}

	return mmQueryRow
}

// ExpectCtxParam1 sets up expected param ctx for Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) ExpectCtxParam1(ctx context.Context) *mPoolMockQueryRow {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	if mmQueryRow.defaultExpectation == nil {
		mmQueryRow.defaultExpectation = &PoolMockQueryRowExpectation{}
	}

	if mmQueryRow.defaultExpectation.params != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Expect")
	}

	if mmQueryRow.defaultExpectation.paramPtrs == nil {
		mmQueryRow.defaultExpectation.paramPtrs = &PoolMockQueryRowParamPtrs{}
	}
	mmQueryRow.defaultExpectation.paramPtrs.ctx = &ctx
	mmQueryRow.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmQueryRow
}

// ExpectSqlParam2 sets up expected param sql for Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) ExpectSqlParam2(sql string) *mPoolMockQueryRow {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	if mmQueryRow.defaultExpectation == nil {
		mmQueryRow.defaultExpectation = &PoolMockQueryRowExpectation{}
	}

	if mmQueryRow.defaultExpectation.params != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Expect")
	}

	if mmQueryRow.defaultExpectation.paramPtrs == nil {
		mmQueryRow.defaultExpectation.paramPtrs = &PoolMockQueryRowParamPtrs{}
	}
	mmQueryRow.defaultExpectation.paramPtrs.sql = &sql
	mmQueryRow.defaultExpectation.expectationOrigins.originSql = minimock.CallerInfo(1)

	return mmQueryRow
}

// ExpectArgsParam3 sets up expected param args for Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) ExpectArgsParam3(args ...any) *mPoolMockQueryRow {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	if mmQueryRow.defaultExpectation == nil {
		mmQueryRow.defaultExpectation = &PoolMockQueryRowExpectation{}
	}

	if mmQueryRow.defaultExpectation.params != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Expect")
	}

	if mmQueryRow.defaultExpectation.paramPtrs == nil {
		mmQueryRow.defaultExpectation.paramPtrs = &PoolMockQueryRowParamPtrs{}
	}
	mmQueryRow.defaultExpectation.paramPtrs.args = &args
	mmQueryRow.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmQueryRow
}

// Inspect accepts an inspector function that has same arguments as the Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) Inspect(f func(ctx context.Context, sql string, args ...any)) *mPoolMockQueryRow {
	if mmQueryRow.mock.inspectFuncQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("Inspect function is already set for PoolMock.QueryRow")
	}

	mmQueryRow.mock.inspectFuncQueryRow = f

	return mmQueryRow
}

// Return sets up results that will be returned by Pool.QueryRow
func (mmQueryRow *mPoolMockQueryRow) Return(r1 pgx.Row) *PoolMock {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	if mmQueryRow.defaultExpectation == nil {
		mmQueryRow.defaultExpectation = &PoolMockQueryRowExpectation{mock: mmQueryRow.mock}
	}
	mmQueryRow.defaultExpectation.results = &PoolMockQueryRowResults{r1}
	mmQueryRow.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmQueryRow.mock
}

// Set uses given function f to mock the Pool.QueryRow method
func (mmQueryRow *mPoolMockQueryRow) Set(f func(ctx context.Context, sql string, args ...any) (r1 pgx.Row)) *PoolMock {
	if mmQueryRow.defaultExpectation != nil {
		mmQueryRow.mock.t.Fatalf("Default expectation is already set for the Pool.QueryRow method")
	}

	if len(mmQueryRow.expectations) > 0 {
		mmQueryRow.mock.t.Fatalf("Some expectations are already set for the Pool.QueryRow method")
	}

	mmQueryRow.mock.funcQueryRow = f
	mmQueryRow.mock.funcQueryRowOrigin = minimock.CallerInfo(1)
	return mmQueryRow.mock
}

// When sets expectation for the Pool.QueryRow which will trigger the result defined by the following
// Then helper
func (mmQueryRow *mPoolMockQueryRow) When(ctx context.Context, sql string, args ...any) *PoolMockQueryRowExpectation {
	if mmQueryRow.mock.funcQueryRow != nil {
		mmQueryRow.mock.t.Fatalf("PoolMock.QueryRow mock is already set by Set")
	}

	expectation := &PoolMockQueryRowExpectation{
		mock:               mmQueryRow.mock,
		params:             &PoolMockQueryRowParams{ctx, sql, args},
		expectationOrigins: PoolMockQueryRowExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmQueryRow.expectations = append(mmQueryRow.expectations, expectation)
	return expectation
}

// Then sets up Pool.QueryRow return parameters for the expectation previously defined by the When method
func (e *PoolMockQueryRowExpectation) Then(r1 pgx.Row) *PoolMock {
	e.results = &PoolMockQueryRowResults{r1}
	return e.mock
}

// Times sets number of times Pool.QueryRow should be invoked
func (mmQueryRow *mPoolMockQueryRow) Times(n uint64) *mPoolMockQueryRow {
	if n == 0 {
		mmQueryRow.mock.t.Fatalf("Times of PoolMock.QueryRow mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmQueryRow.expectedInvocations, n)
	mmQueryRow.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmQueryRow
}

func (mmQueryRow *mPoolMockQueryRow) invocationsDone() bool {
	if len(mmQueryRow.expectations) == 0 && mmQueryRow.defaultExpectation == nil && mmQueryRow.mock.funcQueryRow == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmQueryRow.mock.afterQueryRowCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmQueryRow.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// QueryRow implements Pool
func (mmQueryRow *PoolMock) QueryRow(ctx context.Context, sql string, args ...any) (r1 pgx.Row) {
	mm_atomic.AddUint64(&mmQueryRow.beforeQueryRowCounter, 1)
	defer mm_atomic.AddUint64(&mmQueryRow.afterQueryRowCounter, 1)

	mmQueryRow.t.Helper()

	if mmQueryRow.inspectFuncQueryRow != nil {
		mmQueryRow.inspectFuncQueryRow(ctx, sql, args...)
	}

	mm_params := PoolMockQueryRowParams{ctx, sql, args}

	// Record call args
	mmQueryRow.QueryRowMock.mutex.Lock()
	mmQueryRow.QueryRowMock.callArgs = append(mmQueryRow.QueryRowMock.callArgs, &mm_params)
	mmQueryRow.QueryRowMock.mutex.Unlock()

	for _, e := range mmQueryRow.QueryRowMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1
		}
	}

	if mmQueryRow.QueryRowMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmQueryRow.QueryRowMock.defaultExpectation.Counter, 1)
		mm_want := mmQueryRow.QueryRowMock.defaultExpectation.params
		mm_want_ptrs := mmQueryRow.QueryRowMock.defaultExpectation.paramPtrs

		mm_got := PoolMockQueryRowParams{ctx, sql, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmQueryRow.t.Errorf("PoolMock.QueryRow got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmQueryRow.QueryRowMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sql != nil && !minimock.Equal(*mm_want_ptrs.sql, mm_got.sql) {
				mmQueryRow.t.Errorf("PoolMock.QueryRow got unexpected parameter sql, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmQueryRow.QueryRowMock.defaultExpectation.expectationOrigins.originSql, *mm_want_ptrs.sql, mm_got.sql, minimock.Diff(*mm_want_ptrs.sql, mm_got.sql))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmQueryRow.t.Errorf("PoolMock.QueryRow got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmQueryRow.QueryRowMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmQueryRow.t.Errorf("PoolMock.QueryRow got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmQueryRow.QueryRowMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmQueryRow.QueryRowMock.defaultExpectation.results
		if mm_results == nil {
			mmQueryRow.t.Fatal("No results are set for the PoolMock.QueryRow")
		}
		return (*mm_results).r1
	}
	if mmQueryRow.funcQueryRow != nil {
		return mmQueryRow.funcQueryRow(ctx, sql, args...)
	}
	mmQueryRow.t.Fatalf("Unexpected call to PoolMock.QueryRow. %v %v %v", ctx, sql, args)
	return
}

// QueryRowAfterCounter returns a count of finished PoolMock.QueryRow invocations
func (mmQueryRow *PoolMock) QueryRowAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmQueryRow.afterQueryRowCounter)
}

// QueryRowBeforeCounter returns a count of PoolMock.QueryRow invocations
func (mmQueryRow *PoolMock) QueryRowBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmQueryRow.beforeQueryRowCounter)
}

// Calls returns a list of arguments used in each call to PoolMock.QueryRow.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmQueryRow *mPoolMockQueryRow) Calls() []*PoolMockQueryRowParams {
	mmQueryRow.mutex.RLock()

	argCopy := make([]*PoolMockQueryRowParams, len(mmQueryRow.callArgs))
	copy(argCopy, mmQueryRow.callArgs)

	mmQueryRow.mutex.RUnlock()

	return argCopy
}

// MinimockQueryRowDone returns true if the count of the QueryRow invocations corresponds
// the number of defined expectations
func (m *PoolMock) MinimockQueryRowDone() bool {
	if m.QueryRowMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.QueryRowMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.QueryRowMock.invocationsDone()
}

// MinimockQueryRowInspect logs each unmet expectation
func (m *PoolMock) MinimockQueryRowInspect() {
	for _, e := range m.QueryRowMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PoolMock.QueryRow at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterQueryRowCounter := mm_atomic.LoadUint64(&m.afterQueryRowCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.QueryRowMock.defaultExpectation != nil && afterQueryRowCounter < 1 {
		if m.QueryRowMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PoolMock.QueryRow at\n%s", m.QueryRowMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PoolMock.QueryRow at\n%s with params: %#v", m.QueryRowMock.defaultExpectation.expectationOrigins.origin, *m.QueryRowMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcQueryRow != nil && afterQueryRowCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.QueryRow at\n%s", m.funcQueryRowOrigin)
	}

	if !m.QueryRowMock.invocationsDone() && afterQueryRowCounter > 0 {
		m.t.Errorf("Expected %d calls to PoolMock.QueryRow at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.QueryRowMock.expectedInvocations), m.QueryRowMock.expectedInvocationsOrigin, afterQueryRowCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PoolMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockExecInspect()

			m.MinimockPingInspect()

			m.MinimockQueryRowInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PoolMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PoolMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockExecDone() &&
		m.MinimockPingDone() &&
		m.MinimockQueryRowDone()
}
