// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package postgres

//go:generate minimock -i github.com/Dmitriy-Shcheklein/urlshortener/internal/repository/postgres.Pool -o repository_mock_test.go -n PoolMock -p postgres

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PoolMock implements Pool
type PoolMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPing          func() (err error)
	funcPingOrigin    string
	inspectFuncPing   func()
	afterPingCounter  uint64
	beforePingCounter uint64
	PingMock          mPoolMockPing
}

// NewPoolMock returns a mock for Pool
func NewPoolMock(t minimock.Tester) *PoolMock {
	m := &PoolMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PingMock = mPoolMockPing{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPoolMockPing struct {
	optional           bool
	mock               *PoolMock
	defaultExpectation *PoolMockPingExpectation
	expectations       []*PoolMockPingExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PoolMockPingExpectation specifies expectation struct of the Pool.Ping
type PoolMockPingExpectation struct {
	mock *PoolMock

	results      *PoolMockPingResults
	returnOrigin string
	Counter      uint64
}

// PoolMockPingResults contains results of the Pool.Ping
type PoolMockPingResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPing *mPoolMockPing) Optional() *mPoolMockPing {
	mmPing.optional = true
	return mmPing
}

// Expect sets up expected params for Pool.Ping
func (mmPing *mPoolMockPing) Expect() *mPoolMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("PoolMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &PoolMockPingExpectation{}
	}

	return mmPing
}

// Inspect accepts an inspector function that has same arguments as the Pool.Ping
func (mmPing *mPoolMockPing) Inspect(f func()) *mPoolMockPing {
	if mmPing.mock.inspectFuncPing != nil {
		mmPing.mock.t.Fatalf("Inspect function is already set for PoolMock.Ping")
	}

	mmPing.mock.inspectFuncPing = f

	return mmPing
}

// Return sets up results that will be returned by Pool.Ping
func (mmPing *mPoolMockPing) Return(err error) *PoolMock {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("PoolMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &PoolMockPingExpectation{mock: mmPing.mock}
	}
	mmPing.defaultExpectation.results = &PoolMockPingResults{err}
	mmPing.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Set uses given function f to mock the Pool.Ping method
func (mmPing *mPoolMockPing) Set(f func() (err error)) *PoolMock {
	if mmPing.defaultExpectation != nil {
		mmPing.mock.t.Fatalf("Default expectation is already set for the Pool.Ping method")
	}

	if len(mmPing.expectations) > 0 {
		mmPing.mock.t.Fatalf("Some expectations are already set for the Pool.Ping method")
	}

	mmPing.mock.funcPing = f
	mmPing.mock.funcPingOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Times sets number of times Pool.Ping should be invoked
func (mmPing *mPoolMockPing) Times(n uint64) *mPoolMockPing {
	if n == 0 {
		mmPing.mock.t.Fatalf("Times of PoolMock.Ping mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPing.expectedInvocations, n)
	mmPing.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPing
}

func (mmPing *mPoolMockPing) invocationsDone() bool {
	if len(mmPing.expectations) == 0 && mmPing.defaultExpectation == nil && mmPing.mock.funcPing == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPing.mock.afterPingCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPing.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Ping implements Pool
func (mmPing *PoolMock) Ping() (err error) {
	mm_atomic.AddUint64(&mmPing.beforePingCounter, 1)
	defer mm_atomic.AddUint64(&mmPing.afterPingCounter, 1)

	mmPing.t.Helper()

	if mmPing.inspectFuncPing != nil {
		mmPing.inspectFuncPing()
	}

	if mmPing.PingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPing.PingMock.defaultExpectation.Counter, 1)

		mm_results := mmPing.PingMock.defaultExpectation.results
		if mm_results == nil {
			mmPing.t.Fatal("No results are set for the PoolMock.Ping")
		}
		return (*mm_results).err
	}
	if mmPing.funcPing != nil {
		return mmPing.funcPing()
	}
	mmPing.t.Fatalf("Unexpected call to PoolMock.Ping.")
	return
}

// PingAfterCounter returns a count of finished PoolMock.Ping invocations
func (mmPing *PoolMock) PingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.afterPingCounter)
}

// PingBeforeCounter returns a count of PoolMock.Ping invocations
func (mmPing *PoolMock) PingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.beforePingCounter)
}

// MinimockPingDone returns true if the count of the Ping invocations corresponds
// the number of defined expectations
func (m *PoolMock) MinimockPingDone() bool {
	if m.PingMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingMock.invocationsDone()
}

// MinimockPingInspect logs each unmet expectation
func (m *PoolMock) MinimockPingInspect() {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to PoolMock.Ping")
		}
	}

	afterPingCounter := mm_atomic.LoadUint64(&m.afterPingCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.Ping at\n%s", m.PingMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to PoolMock.Ping at\n%s", m.funcPingOrigin)
	}

	if !m.PingMock.invocationsDone() && afterPingCounter > 0 {
		m.t.Errorf("Expected %d calls to PoolMock.Ping at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingMock.expectedInvocations), m.PingMock.expectedInvocationsOrigin, afterPingCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PoolMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPingInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PoolMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PoolMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPingDone()
}
